name = "houfy-uat-proxy"
main = "workers/houfy-uat-proxy.js"
compatibility_date = "2025-08-29"

account_id = "34c3d57ed1b72bfcee734c13ddbeedaa"
workers_dev = false

# Routes for UAT environment
routes = [
  { pattern = "uat.skyforestgetaway.com/*", zone_name = "skyforestgetaway.com" }
]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
ENVIRONMENT = "uat"
CDN_URL = "https://cdn-uat.skyforestgetaway.com/public/"
MANIFEST_URL = "https://raw.githubusercontent.com/jjkaye/houfy-assets/uat/public/js/manifest.json"

# Staging guard controls
REQUIRE_AUTH = "true"
FORCE_NOINDEX = "true"
SERVE_ROBOTS = "true"
CANONICAL_BASE = "https://skyforestgetaway.com"